// !!!! DO NOT EDIT !!!, use: make config

#ifndef _CONFIG_H_
#define _CONFIG_H_

// CONFIG_DEBUG is not set
// USE_LCD_CHARGE_PUMP is not set
#define USE_WATCHDOG
#define CONFIG_RUNLOOP_INDICATOR
#define CONFIG_RTC_IRQ
#define CONFIG_RTC_DST
#define CONFIG_RTC_DST_ZONE 4
// CONFIG_TIMER_4S_IRQ is not set
#ifndef CONFIG_BUTTONS_LONG_PRESS_TIME
#define CONFIG_BUTTONS_LONG_PRESS_TIME 20
#endif // CONFIG_BUTTONS_LONG_PRESS_TIME
#ifndef CONFIG_BUTTONS_SHORT_PRESS_TIME
#define CONFIG_BUTTONS_SHORT_PRESS_TIME 1
#endif // CONFIG_BUTTONS_SHORT_PRESS_TIME
// CONFIG_BUTTONS_SWAP_UP_AND_DOWN is not set
#define CONFIG_BATTERY_MONITOR
// CONFIG_BATTERY_DISABLE_FILTER is not set
#ifndef CONFIG_TEMPERATURE_OFFSET
#define CONFIG_TEMPERATURE_OFFSET -260
#endif // CONFIG_TEMPERATURE_OFFSET
#define CONFIG_TEMPERATURE_METRIC
#define CONFIG_MOD_CLOCK
#define CONFIG_MOD_CLOCK_BLINKCOL
// CONFIG_MOD_CLOCK_AMPM is not set
#define CONFIG_MOD_CLOCK_MONTH_FIRST
#define CONFIG_MOD_STOPWATCH
#define CONFIG_MOD_ALARM
#define CONFIG_MOD_TEMPERATURE
#define CONFIG_MOD_BATTERY
#define CONFIG_MOD_BATTERY_SHOW_VOLTAGE
#define CONFIG_MOD_RESET
// CONFIG_MOD_RESET_EASY_RESET is not set
// CONFIG_MOD_ACCELEROMETER is not set
#define CONFIG_MOD_MUSIC
#define CONFIG_MOD_TIDE
// CONFIG_MOD_BUZZTEST is not set
// CONFIG_MOD_OTP is not set
#define CONFIG_MOD_OTP_KEYS { { "A","",0 } }
#define CONFIG_MOD_OTP_OFFSET 0
// CONFIG_MOD_OTP_SOUND_CUE is not set

#endif // _CONFIG_H_
